version: "3"

services:
  sonarqube:
    image: r3xakead0/sonarqubewithsqlplugin:1.0
    ports:
      - "9000:9000"
    networks:
      - sonarnet
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgres:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    volumes:
      - /c/docker-data/sonarqube_conf:/opt/sonarqube/conf
      - /c/docker-data/sonarqube_data:/opt/sonarqube/data
      - /c/docker-data/sonarqube_extensions:/opt/sonarqube/extensions
      - /c/docker-data/sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

networks:
  sonarnet:
    driver: bridge

volumes:
  postgresql:
  postgresql_data: